name: Сборка и публикация Docker-образа

on:
  push:
    tags:
      - 'v*.*.*' # Запускать при создании тегов вида v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Настройка Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Авторизация в GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Извлечение версии из тега
      id: extract_tag
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo "::set-output name=version::$TAG"

    - name: Сборка и публикация Docker-образа
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.version }}
        cache-from: type=gha,scope=${{ github.workflow }}-${{ github.job }}
        cache-to: type=gha,scope=${{ github.workflow }}-${{ github.job }},mode=max
